# Generated by Django 5.2.17 on 2026-09-20 19:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='检测项目编码')),
                ('name', models.CharField(max_length=128, verbose_name='检测项目')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='单位')),
                ('method', models.CharField(blank=True, max_length=128, verbose_name='方法')),
                ('lower_spec', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='质量标准下限')),
                ('upper_spec', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='质量标准上限')),
            ],
            options={
                'verbose_name': '检测项目',
                'verbose_name_plural': '检测项目',
            },
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='恒温箱编号')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('location', models.CharField(blank=True, max_length=128, verbose_name='位置')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用中')),
            ],
            options={
                'verbose_name': '恒温箱',
                'verbose_name_plural': '恒温箱',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='产品编码')),
                ('name', models.CharField(max_length=128, verbose_name='产品名称')),
                ('dosage_form', models.CharField(blank=True, max_length=32, verbose_name='剂型')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='StorageCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='储存条件编码')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('temp_low', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='温度下限 ℃')),
                ('temp_high', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='温度上限 ℃')),
                ('humidity_low', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='湿度下限 %RH')),
                ('humidity_high', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='湿度上限 %RH')),
            ],
            options={
                'verbose_name': '储存条件',
                'verbose_name_plural': '储存条件',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('power_outage', '断电'), ('temp_excursion', '温度偏离'), ('door_open', '长时间开门'), ('other', '其他')], max_length=16, verbose_name='事件类型')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('min_temp', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='期间最低温度 ℃')),
                ('max_temp', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='期间最高温度 ℃')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.chamber', verbose_name='恒温箱')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logged_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '箱体环境事件',
                'verbose_name_plural': '箱体环境事件',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure_started_at', models.DateTimeField(verbose_name='暴露开始')),
                ('exposure_ended_at', models.DateTimeField(verbose_name='暴露结束')),
                ('minutes_exposed', models.PositiveIntegerField(verbose_name='暴露时长(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exposures', to='core.environmentevent', verbose_name='环境事件')),
            ],
            options={
                'verbose_name': '偏离暴露',
                'verbose_name_plural': '偏离暴露',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpactAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('release', '放行解冻'), ('exclude', '排除影响单元'), ('additional', '追加考察')], max_length=16, verbose_name='评估结论')),
                ('comment', models.TextField(blank=True, verbose_name='评估说明')),
                ('assessed_at', models.DateTimeField(auto_now=True, verbose_name='评估时间')),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='QA 评估人')),
                ('exposure', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='impact_assessment', to='core.exposure', verbose_name='暴露记录')),
            ],
            options={
                'verbose_name': '影响评估',
                'verbose_name_plural': '影响评估',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='方案编号')),
                ('title', models.CharField(max_length=200, verbose_name='方案标题')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocols', to='core.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '稳定性方案',
                'verbose_name_plural': '稳定性方案',
            },
        ),
        migrations.CreateModel(
            name='ProtocolVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.CharField(max_length=16, verbose_name='版本号')),
                ('status', models.CharField(choices=[('draft', '草案'), ('effective', '生效'), ('superseded', '被替代')], default='draft', max_length=16, verbose_name='状态')),
                ('default_pull_window_hours', models.PositiveIntegerField(default=48, verbose_name='默认取样窗口(小时)')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.protocol', verbose_name='方案')),
                ('storage_condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.storagecondition', verbose_name='储存条件')),
            ],
            options={
                'verbose_name': '方案版本',
                'verbose_name_plural': '方案版本',
                'ordering': ['protocol__code', '-created_at'],
                'unique_together': {('protocol', 'version_no')},
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=32, unique=True, verbose_name='批号')),
                ('manufacturing_date', models.DateField(verbose_name='生产日期(稳定性零点)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.chamber', verbose_name='放置恒温箱')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.product', verbose_name='产品')),
                ('protocol_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.protocolversion', verbose_name='入组方案版本')),
            ],
            options={
                'verbose_name': '批次',
                'verbose_name_plural': '批次',
            },
        ),
        migrations.CreateModel(
            name='SampleUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=64, unique=True, verbose_name='样品条码')),
                ('status', models.CharField(choices=[('available', '在箱可用'), ('consumed', '已消耗'), ('damaged', '破损'), ('misplaced', '错放/失联'), ('withdrawn', '已退出')], default='available', max_length=16, verbose_name='状态')),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入箱时间')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='消耗时间')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='core.batch', verbose_name='批号')),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='core.chamber', verbose_name='所在恒温箱')),
            ],
            options={
                'verbose_name': '样品单元',
                'verbose_name_plural': '样品单元',
                'ordering': ['batch__batch_no', 'barcode'],
            },
        ),
        migrations.AddField(
            model_name='exposure',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exposures', to='core.sampleunit', verbose_name='暴露样品'),
        ),
        migrations.CreateModel(
            name='ScheduledAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepoint_code', models.CharField(max_length=16, verbose_name='时间点标识(快像)')),
                ('offset_days', models.PositiveIntegerField(verbose_name='偏移天数(快像)')),
                ('kind', models.CharField(choices=[('scheduled', '计划取样'), ('replacement', '替代取样'), ('extra', '追加考察')], default='scheduled', max_length=16, verbose_name='动作类型')),
                ('status', models.CharField(choices=[('pending', '待取样'), ('pulled', '已取样'), ('frozen', '冻结待评估'), ('void', '已作废')], default='pending', max_length=16, verbose_name='状态')),
                ('planned_at', models.DateTimeField(verbose_name='计划取样时间')),
                ('window_start', models.DateTimeField(verbose_name='窗口开始')),
                ('window_end', models.DateTimeField(verbose_name='窗口结束')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='分配时间')),
                ('freeze_reason', models.CharField(blank=True, choices=[('temp_excursion', '温度偏离'), ('damaged', '样品破损'), ('misplaced', '样品错放')], max_length=32, null=True, verbose_name='冻结原因')),
                ('frozen_at', models.DateTimeField(blank=True, null=True, verbose_name='冻结时间')),
                ('freeze_note', models.CharField(blank=True, max_length=255, verbose_name='冻结说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='core.batch', verbose_name='批次')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_actions', to=settings.AUTH_USER_MODEL)),
                ('protocol_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='core.protocolversion', verbose_name='方案版本快像')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='core.scheduledaction', verbose_name='替代的原动作')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='core.sampleunit', verbose_name='分配样品')),
            ],
            options={
                'verbose_name': '取样动作',
                'verbose_name_plural': '取样动作',
                'ordering': ['batch__batch_no', 'planned_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SamplingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulled_at', models.DateTimeField(verbose_name='实际取样时间')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pulled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samplings', to=settings.AUTH_USER_MODEL, verbose_name='取样人')),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sampling_event', to='core.scheduledaction', verbose_name='动作')),
            ],
            options={
                'verbose_name': '实际取样记录',
                'verbose_name_plural': '实际取样记录',
            },
        ),
        migrations.AddField(
            model_name='chamber',
            name='storage_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.storagecondition', verbose_name='规定储存条件'),
        ),
        migrations.CreateModel(
            name='TimePointDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='时间点标识')),
                ('offset_days', models.PositiveIntegerField(verbose_name='距零点天数')),
                ('window_before_hours', models.PositiveIntegerField(default=48, verbose_name='窗口提前小时数')),
                ('window_after_hours', models.PositiveIntegerField(default=48, verbose_name='窗口延后小时数')),
                ('assays', models.ManyToManyField(related_name='timepoints', to='core.assay', verbose_name='检测项目')),
                ('protocol_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timepoints', to='core.protocolversion', verbose_name='方案版本')),
            ],
            options={
                'verbose_name': '计划时间点定义',
                'verbose_name_plural': '计划时间点定义',
                'ordering': ['protocol_version', 'offset_days'],
                'unique_together': {('protocol_version', 'code')},
            },
        ),
        migrations.AddField(
            model_name='scheduledaction',
            name='timepoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='core.timepointdefinition', verbose_name='计划时间点'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('coordinator', '协调员'), ('analyst', '分析员'), ('qa', '质量人员')], max_length=16, verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
            },
        ),
        migrations.AlterUniqueTogether(
            name='exposure',
            unique_together={('sample', 'event')},
        ),
        migrations.CreateModel(
            name='AssayResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, verbose_name='结果值')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='检测时间')),
                ('is_frozen', models.BooleanField(default=False, verbose_name='冻结待评估')),
                ('freeze_reason', models.CharField(blank=True, choices=[('temp_excursion', '温度偏离'), ('damaged', '样品破损'), ('misplaced', '样品错放')], max_length=32, null=True, verbose_name='冻结原因')),
                ('frozen_at', models.DateTimeField(blank=True, null=True, verbose_name='冻结时间')),
                ('disposition', models.CharField(choices=[('pending_review', '待判定'), ('included', '纳入'), ('excluded', '排除'), ('additional', '追加考察')], default='pending_review', max_length=16, verbose_name='QA 处置')),
                ('disposition_at', models.DateTimeField(blank=True, null=True, verbose_name='处置时间')),
                ('disposition_comment', models.CharField(blank=True, max_length=255, verbose_name='处置说明')),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='core.assay', verbose_name='检测项目')),
                ('disposition_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposed_results', to=settings.AUTH_USER_MODEL, verbose_name='QA 处置人')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_results', to=settings.AUTH_USER_MODEL, verbose_name='分析员')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='core.scheduledaction', verbose_name='取样动作')),
            ],
            options={
                'verbose_name': '检测结果',
                'verbose_name_plural': '检测结果',
                'ordering': ['action__batch__batch_no', 'action__planned_at', 'assay__code'],
                'unique_together': {('action', 'assay')},
            },
        ),
        migrations.AddConstraint(
            model_name='scheduledaction',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'scheduled')), fields=('batch', 'timepoint'), name='uniq_scheduled_action_per_batch_timepoint'),
        ),
    ]
