# Generated by Django 5.2.17 on 2026-09-20 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledaction',
            name='timepoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='core.timepointdefinition', verbose_name='计划时间点'),
        ),
    ]
