# Generated by Django 5.2.17 on 2026-09-20 18:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='恒温箱编号')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='名称')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='位置')),
                ('condition_note', models.CharField(blank=True, max_length=160, verbose_name='设定条件')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=40, verbose_name='产品编号')),
                ('product_name', models.CharField(blank=True, max_length=160, verbose_name='产品名称')),
                ('batch_number', models.CharField(max_length=40, unique=True, verbose_name='批号')),
                ('storage_start', models.DateTimeField(verbose_name='入库时间（考察零点）')),
                ('status', models.CharField(choices=[('active', '考察中'), ('completed', '已完成'), ('terminated', '已终止')], default='active', max_length=16)),
                ('plan_generated', models.BooleanField(default=False, verbose_name='是否已编排计划')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='stability.chamber', verbose_name='恒温箱')),
            ],
            options={
                'ordering': ('batch_number',),
            },
        ),
        migrations.CreateModel(
            name='ChamberEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('power_out', '断电'), ('temp_excursion', '温度偏离'), ('door_open', '长时间开门'), ('equipment_failure', '设备故障'), ('other', '其他')], max_length=24, verbose_name='事件类型')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, help_text='为空表示事件仍在持续', null=True, verbose_name='结束时间')),
                ('observed_min_temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='实测最低温度 ℃')),
                ('observed_max_temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='实测最高温度 ℃')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('open', '待评估'), ('under_review', '评估中'), ('no_impact', '评估完成-无影响'), ('impact', '评估完成-有影响')], default='open', max_length=20, verbose_name='评估状态')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_at', models.DateTimeField(blank=True, null=True, verbose_name='评估时间')),
                ('assessment_note', models.TextField(blank=True, verbose_name='评估结论说明')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_assessed', to=settings.AUTH_USER_MODEL, verbose_name='评估人')),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='stability.chamber', verbose_name='恒温箱')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_recorded', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='PlannedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_code', models.CharField(max_length=20, verbose_name='时间点编号（快照）')),
                ('point_name', models.CharField(blank=True, max_length=80, verbose_name='时间点名称（快照）')),
                ('planned_datetime', models.DateTimeField(verbose_name='计划取样时间')),
                ('window_start', models.DateTimeField(verbose_name='窗口开始')),
                ('window_end', models.DateTimeField(verbose_name='窗口结束')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='stability.batch', verbose_name='批次')),
            ],
            options={
                'ordering': ('planned_datetime', 'test_item__code'),
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='方案编号')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('title', models.CharField(max_length=200, verbose_name='方案名称')),
                ('status', models.CharField(choices=[('draft', '草案'), ('active', '现行'), ('superseded', '被替代'), ('retired', '废止')], default='draft', max_length=20)),
                ('effective_date', models.DateField(verbose_name='生效日期')),
                ('notes', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocols_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='stability.protocol', verbose_name='替代的方案版本')),
            ],
            options={
                'ordering': ('code', '-version'),
                'unique_together': {('code', 'version')},
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='stability.protocol', verbose_name='方案版本'),
        ),
        migrations.CreateModel(
            name='SampleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('original', '原计划样品'), ('substitute', '替代样品')], max_length=12)),
                ('state', models.CharField(choices=[('active', '有效'), ('failed', '已失败（样品不可用）')], default='active', max_length=12)),
                ('reason', models.CharField(blank=True, choices=[('damaged', '破损'), ('misplaced', '错放/遗失'), ('lost', '灭失'), ('early_withdrawal', '提前取出'), ('insufficient', '样品量不足'), ('other', '其他')], max_length=20, verbose_name='替代原因')),
                ('note', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='stability.plannedaction', verbose_name='计划动作')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='安排人')),
                ('substitutes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='stability.sampleassignment', verbose_name='替代的分配')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SampleUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=40, unique=True, verbose_name='样品条码')),
                ('status', models.CharField(choices=[('in_storage', '在箱'), ('reserved', '已分配'), ('withdrawn', '已取出'), ('consumed', '已检验消耗'), ('damaged', '破损'), ('misplaced', '错放/遗失')], default='in_storage', max_length=16, verbose_name='状态')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='实际取出时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='stability.batch', verbose_name='批次')),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_withdrawn', to=settings.AUTH_USER_MODEL, verbose_name='取出操作人')),
            ],
            options={
                'ordering': ('batch', 'barcode'),
            },
        ),
        migrations.CreateModel(
            name='SampleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('misplaced', '错放/找不到样品'), ('damaged', '破损'), ('wrong_location', '存放位置错误'), ('early_withdrawal', '提前取出'), ('late_withdrawal', '逾期取出'), ('other', '其他')], max_length=20, verbose_name='异常类型')),
                ('occurred_at', models.DateTimeField(verbose_name='发生时间')),
                ('note', models.TextField(blank=True, verbose_name='说明')),
                ('disposition', models.CharField(choices=[('pending', '待影响评估'), ('no_impact', '无影响'), ('impact', '有影响')], default='pending', max_length=16, verbose_name='影响评估')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_at', models.DateTimeField(blank=True, null=True, verbose_name='评估时间')),
                ('assessment_note', models.TextField(blank=True, verbose_name='评估说明')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions_assessed', to=settings.AUTH_USER_MODEL, verbose_name='评估人')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='stability.sampleassignment', verbose_name='关联分配')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions_recorded', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='stability.sampleunit', verbose_name='样品')),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.AddField(
            model_name='sampleassignment',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='stability.sampleunit', verbose_name='样品'),
        ),
        migrations.CreateModel(
            name='SamplingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='时间点编号')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='时间点名称')),
                ('offset_days', models.PositiveIntegerField(verbose_name='距入库天数')),
                ('window_before_days', models.PositiveIntegerField(default=0, verbose_name='窗口提前天数')),
                ('window_after_days', models.PositiveIntegerField(default=0, verbose_name='窗口延后天数')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='stability.protocol', verbose_name='方案')),
            ],
            options={
                'ordering': ('protocol', 'order', 'offset_days', 'code'),
            },
        ),
        migrations.AddField(
            model_name='plannedaction',
            name='sampling_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='stability.samplingpoint', verbose_name='计划时间点'),
        ),
        migrations.CreateModel(
            name='StorageCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='条件编号')),
                ('label', models.CharField(max_length=120, verbose_name='条件名称')),
                ('target_temperature_c', models.DecimalField(decimal_places=2, default=Decimal('5.0'), max_digits=5, verbose_name='目标温度 ℃')),
                ('target_humidity_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='目标相对湿度 %')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='stability.protocol', verbose_name='方案')),
            ],
            options={
                'ordering': ('protocol', 'code'),
                'unique_together': {('protocol', 'code')},
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='storage_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='stability.storagecondition', verbose_name='储存条件'),
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='项目编号')),
                ('name', models.CharField(max_length=120, verbose_name='项目名称')),
                ('method', models.CharField(blank=True, max_length=160, verbose_name='检验方法')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='单位')),
                ('specification', models.CharField(blank=True, max_length=240, verbose_name='质量标准')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_items', to='stability.protocol', verbose_name='方案')),
            ],
            options={
                'ordering': ('protocol', 'code'),
                'unique_together': {('protocol', 'code')},
            },
        ),
        migrations.AddField(
            model_name='samplingpoint',
            name='test_items',
            field=models.ManyToManyField(related_name='points', to='stability.testitem', verbose_name='该点检测项目'),
        ),
        migrations.AddField(
            model_name='plannedaction',
            name='test_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='stability.testitem', verbose_name='检测项目'),
        ),
        migrations.AlterUniqueTogether(
            name='samplingpoint',
            unique_together={('protocol', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='plannedaction',
            unique_together={('batch', 'sampling_point', 'test_item')},
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='数值结果')),
                ('value_text', models.CharField(blank=True, max_length=240, verbose_name='文字结果')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='单位')),
                ('analyzed_at', models.DateTimeField(verbose_name='实际检测时间')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('qa_status', models.CharField(choices=[('pending', '待质量判定'), ('included', '纳入'), ('excluded', '排除'), ('additional', '追加考察')], default='pending', max_length=12, verbose_name='质量判定')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='判定时间')),
                ('decision_note', models.TextField(blank=True, verbose_name='判定说明')),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results_submitted', to=settings.AUTH_USER_MODEL, verbose_name='分析员')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='stability.sampleassignment', verbose_name='执行分配')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_decided', to=settings.AUTH_USER_MODEL, verbose_name='判定人')),
                ('test_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='stability.testitem', verbose_name='检测项目')),
            ],
            options={
                'ordering': ('-analyzed_at',),
                'unique_together': {('assignment', 'test_item')},
            },
        ),
    ]
